In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
path = r"D:\CNTT\py_for_da\crawl_data_analyst\tiki\suckhoe_lamdep\nh"
os.listdir(path)

['.ipynb_checkpoints',
 'tk_sk&ld_nh_npage - Copy (8).ipynb',
 'tk_sk&ld_nh_t10.csv',
 'tk_sk&ld_nh_t11.csv',
 'tk_sk&ld_nh_t12.csv',
 'tk_sk&ld_nh_t13.csv',
 'tk_sk&ld_nh_t14.csv',
 'tk_sk&ld_nh_t15.csv',
 'tk_sk&ld_nh_t16.csv',
 'tk_sk&ld_nh_t17.csv',
 'tk_sk&ld_nh_t18.csv',
 'tk_sk&ld_nh_t19.csv',
 'tk_sk&ld_nh_t2.csv',
 'tk_sk&ld_nh_t20.csv',
 'tk_sk&ld_nh_t21.csv',
 'tk_sk&ld_nh_t22.csv',
 'tk_sk&ld_nh_t23.csv',
 'tk_sk&ld_nh_t24.csv',
 'tk_sk&ld_nh_t25.csv',
 'tk_sk&ld_nh_t26.csv',
 'tk_sk&ld_nh_t27.csv',
 'tk_sk&ld_nh_t28.csv',
 'tk_sk&ld_nh_t29.csv',
 'tk_sk&ld_nh_t3.csv',
 'tk_sk&ld_nh_t30.csv',
 'tk_sk&ld_nh_t31.csv',
 'tk_sk&ld_nh_t32.csv',
 'tk_sk&ld_nh_t33.csv',
 'tk_sk&ld_nh_t34.csv',
 'tk_sk&ld_nh_t35.csv',
 'tk_sk&ld_nh_t36.csv',
 'tk_sk&ld_nh_t37.csv',
 'tk_sk&ld_nh_t38.csv',
 'tk_sk&ld_nh_t39.csv',
 'tk_sk&ld_nh_t4.csv',
 'tk_sk&ld_nh_t40.csv',
 'tk_sk&ld_nh_t41.csv',
 'tk_sk&ld_nh_t42.csv',
 'tk_sk&ld_nh_t43.csv',
 'tk_sk&ld_nh_t5.csv',
 'tk_sk&ld_nh_t6.csv',
 'tk_sk&ld_nh_t7.csv',
 'tk_sk&ld_nh_t8.csv',
 'tk_sk&ld_nh_t9.csv',
 'tk_sk&ld_nuochoa_all.ipynb']

In [3]:
frames = []
for file in os.listdir(path):
    if file.endswith('.csv'):
        filepath = path + '\\' + file
        df1 = pd.read_csv(filepath)
        frames.append(df1)
        result = pd.concat(frames)

df_all = result
df_all.to_csv("tk_sk&ld_nuochoa_all.csv", index="False")

In [4]:
df_all

,title,price,link_item,index,discount,sales
0,Nước Hoa Nam Carolina Herrera 212 Vip Men Edt ...,2.310.000₫,https://tiki.vn/nuoc-hoa-nam-carolina-herrera-...,1,NaN,Đã bán 12
1,Nước hoa vùng kín nữ - Midnight Forest Eau De...,259.000₫,https://tiki.vn/nuoc-hoa-vung-kin-nu-midnight-...,2,-25%,Đã bán 9
2,Body Mist Japanese Cherry Blossom 236ml - Bath...,249.000₫,https://tiki.vn/body-mist-japanese-cherry-blos...,3,-30%,NaN
3,Nước hoa vùng kín nữ - Honey Valley Eau De Pa...,85.000₫,https://tiki.vn/nuoc-hoa-vung-kin-nu-honey-val...,4,NaN,Đã bán 24
4,NaN,NaN,https://tiki.vn/tinh-dau-nuoc-hoa-dubai_-sulta...,5,-8%,NaN
...,...,...,...,...,...,...
35,NaN,NaN,https://tiki.vn/tinh-dau-nuoc-hoa-dubai_-cleve...,36,NaN,NaN
36,Nước Hoa Cao Cấp Nomad Nhập Khẩu Ý - Sang Trọn...,189.000₫,https://tiki.vn/nuoc-hoa-cao-cap-nomad-nhap-kh...,37,NaN,NaN
37,Nước hoa vùng kín X2 Sexy Cocayhoala 5ml khử m...,220.000₫,https://tiki.vn/nuoc-hoa-vung-kin-x2-sexy-coca...,38,NaN,Đã bán 27
38,"Nước hoa nam, nữ xịt body lotion xịt thơm cơ t...",418.000₫,https://tiki.vn/nuoc-hoa-nam--nu-xit-body-loti...,39,NaN,Đã bán 9
39,Nước Hoa Mini Violet Velvet Perfume 30ml,92.800₫,https://tiki.vn/nuoc-hoa-mini-violet-velvet-pe...,40,NaN,NaN

1. Xử lý dữ liệu

In [5]:
df_all.dropna(subset=['price'], inplace=True)

In [6]:
df_all = df_all.drop('index', axis=1)

In [7]:
df_all = df_all.reset_index(drop=True)

In [8]:
df_all

,title,price,link_item,discount,sales
0,Nước Hoa Nam Carolina Herrera 212 Vip Men Edt ...,2.310.000₫,https://tiki.vn/nuoc-hoa-nam-carolina-herrera-...,NaN,Đã bán 12
1,Nước hoa vùng kín nữ - Midnight Forest Eau De...,259.000₫,https://tiki.vn/nuoc-hoa-vung-kin-nu-midnight-...,-25%,Đã bán 9
2,Body Mist Japanese Cherry Blossom 236ml - Bath...,249.000₫,https://tiki.vn/body-mist-japanese-cherry-blos...,-30%,NaN
3,Nước hoa vùng kín nữ - Honey Valley Eau De Pa...,85.000₫,https://tiki.vn/nuoc-hoa-vung-kin-nu-honey-val...,NaN,Đã bán 24
4,Nước Hoa Nam Gucci Guilty Parfum Pour Homme,2.080.000₫,https://tiki.vn/nuoc-hoa-nam-gucci-guilty-parf...,-14%,Đã bán 1
...,...,...,...,...,...
1362,Body Mist Pure Wonder 236ml - Bath and Body Wo...,249.000₫,https://tiki.vn/body-mist-pure-wonder-236ml-ba...,NaN,NaN
1363,Nước Hoa Cao Cấp Nomad Nhập Khẩu Ý - Sang Trọn...,189.000₫,https://tiki.vn/nuoc-hoa-cao-cap-nomad-nhap-kh...,NaN,NaN
1364,Nước hoa vùng kín X2 Sexy Cocayhoala 5ml khử m...,220.000₫,https://tiki.vn/nuoc-hoa-vung-kin-x2-sexy-coca...,NaN,Đã bán 27
1365,"Nước hoa nam, nữ xịt body lotion xịt thơm cơ t...",418.000₫,https://tiki.vn/nuoc-hoa-nam--nu-xit-body-loti...,NaN,Đã bán 9
1366,Nước Hoa Mini Violet Velvet Perfume 30ml,92.800₫,https://tiki.vn/nuoc-hoa-mini-violet-velvet-pe...,NaN,NaN

In [9]:
df_all["price"] = df_all["price"].replace('[\₫,]', '', regex=True).replace('\.', '', regex=True).astype(int)
print(df_all["price"])

0       2310000
1        259000
2        249000
3         85000
4       2080000
         ...
1362     249000
1363     189000
1364     220000
1365     418000
1366      92800
Name: price, Length: 1367, dtype: int32

In [10]:
def convert_to_number(value):
    if isinstance(value, str):
        if 'k+' in value:
            return float(value.replace('k+', '')) * 1000
        elif 'k' in value:
            return float(value.replace('k', '')) * 1000
        else:
            return float(value) if value else None
    else:
        return value

In [11]:
# Áp dụng hàm convert_to_number cho cột 'Gia'
df_all["sales"] = df_all["sales"].apply(lambda x: np.nan if pd.isna(x) else x.split('Đã bán')[1].strip())
df_all["sales"] = df_all["sales"].apply(convert_to_number)
df_all["sales"]

0       12.0
1        9.0
2        NaN
3       24.0
4        1.0
        ...
1362     NaN
1363     NaN
1364    27.0
1365     9.0
1366     NaN
Name: sales, Length: 1367, dtype: float64

In [12]:
df_all["revenue"] = df_all["price"] * df_all["sales"]
df_all["revenue"]

0       27720000.0
1        2331000.0
2              NaN
3        2040000.0
4        2080000.0
           ...
1362           NaN
1363           NaN
1364     5940000.0
1365     3762000.0
1366           NaN
Name: revenue, Length: 1367, dtype: float64

In [13]:
total = df_all["revenue"].sum()

In [14]:
print("Tổng doanh số nước hoa: ", total)

Tổng doanh số nước hoa:  4781526890.0

In [15]:
df_all

,title,price,link_item,discount,sales,revenue
0,Nước Hoa Nam Carolina Herrera 212 Vip Men Edt ...,2310000,https://tiki.vn/nuoc-hoa-nam-carolina-herrera-...,NaN,12.0,27720000.0
1,Nước hoa vùng kín nữ - Midnight Forest Eau De...,259000,https://tiki.vn/nuoc-hoa-vung-kin-nu-midnight-...,-25%,9.0,2331000.0
2,Body Mist Japanese Cherry Blossom 236ml - Bath...,249000,https://tiki.vn/body-mist-japanese-cherry-blos...,-30%,NaN,NaN
3,Nước hoa vùng kín nữ - Honey Valley Eau De Pa...,85000,https://tiki.vn/nuoc-hoa-vung-kin-nu-honey-val...,NaN,24.0,2040000.0
4,Nước Hoa Nam Gucci Guilty Parfum Pour Homme,2080000,https://tiki.vn/nuoc-hoa-nam-gucci-guilty-parf...,-14%,1.0,2080000.0
...,...,...,...,...,...,...
1362,Body Mist Pure Wonder 236ml - Bath and Body Wo...,249000,https://tiki.vn/body-mist-pure-wonder-236ml-ba...,NaN,NaN,NaN
1363,Nước Hoa Cao Cấp Nomad Nhập Khẩu Ý - Sang Trọn...,189000,https://tiki.vn/nuoc-hoa-cao-cap-nomad-nhap-kh...,NaN,NaN,NaN
1364,Nước hoa vùng kín X2 Sexy Cocayhoala 5ml khử m...,220000,https://tiki.vn/nuoc-hoa-vung-kin-x2-sexy-coca...,NaN,27.0,5940000.0
1365,"Nước hoa nam, nữ xịt body lotion xịt thơm cơ t...",418000,https://tiki.vn/nuoc-hoa-nam--nu-xit-body-loti...,NaN,9.0,3762000.0
1366,Nước Hoa Mini Violet Velvet Perfume 30ml,92800,https://tiki.vn/nuoc-hoa-mini-violet-velvet-pe...,NaN,NaN,NaN

In [16]:
df_all.to_csv("tk_sk&ld_nuochoa_all_ed.csv")